package es.mpt.dsic.eeutil.service.sia.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.3 2016-09-28T15:00:53.368+02:00 Generated source
 * version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://www.map.es/sgca/consultar",
    name = "wsSIAConsultarActuacionesIdentificacion")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WsSIAConsultarActuacionesIdentificacion {

  @WebResult(name = "enviaSIA",
      targetNamespace = "http://www.map.es/sgca/consultar/messages/v2_4/EnviaSIA",
      partName = "parameters")
  @WebMethod(operationName = "consultarSIA_v2_4",
      action = "http://www.map.es/sgca/consultar/consultarSIA_v2_4")
  public EnviaSIA consultarSIAV24(@WebParam(partName = "parameters", name = "paramSIA",
      targetNamespace = "http://www.map.es/sgca/consultar/messages/v2_4/ParamSIA") ParamSIA2 parameters);

  @WebResult(name = "enviaSIA",
      targetNamespace = "http://www.map.es/sgca/consultar/messages/EnviaSIA",
      partName = "parameters")
  @WebMethod(action = "http://www.map.es/sgca/consultar/consultarSIA")
  public EnviaSIA3 consultarSIA(@WebParam(partName = "parameters", name = "paramSIA",
      targetNamespace = "http://www.map.es/sgca/consultar/messages/ParamSIA") ParamSIA parameters);

  @WebResult(name = "enviaSIA",
      targetNamespace = "http://www.map.es/sgca/consultar/messages/v3_0/EnviaSIA",
      partName = "parameters")
  @WebMethod(operationName = "consultarSIA_v3_0",
      action = "http://www.map.es/sgca/consultar/consultarSIA_v3_0")
  public EnviaSIA2 consultarSIAV30(@WebParam(partName = "parameters", name = "paramSIA",
      targetNamespace = "http://www.map.es/sgca/consultar/messages/v3_0/ParamSIA") ParamSIA3 parameters);
}
