
package es.mpt.dsic.eeutil.service.sia.model;

/**
 * Please modify this class to meet your needs This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * This class was generated by Apache CXF 3.0.3 2016-09-28T15:00:53.326+02:00 Generated source
 * version: 3.0.3
 * 
 */
public final class WsSIAConsultarActuacionesIdentificacion_WsSIAConsultarActuacionesIdentificacionSOAP_Client {

  protected static final Log logger = LogFactory.getLog(
      WsSIAConsultarActuacionesIdentificacion_WsSIAConsultarActuacionesIdentificacionSOAP_Client.class);
  private static final QName SERVICE_NAME =
      new QName("http://www.map.es/sgca/consultar", "wsSIAConsultarActuacionesIdentificacion");

  private WsSIAConsultarActuacionesIdentificacion_WsSIAConsultarActuacionesIdentificacionSOAP_Client() {}

  public static void main(String args[]) throws java.lang.Exception {
    URL wsdlURL = WsSIAConsultarActuacionesIdentificacion_Service.WSDL_LOCATION;
    if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
      File wsdlFile = new File(args[0]);
      try {
        if (wsdlFile.exists()) {
          wsdlURL = wsdlFile.toURI().toURL();
        } else {
          wsdlURL = new URL(args[0]);
        }
      } catch (MalformedURLException e) {
        logger.error(e.getMessage(), e);
      }
    }

    WsSIAConsultarActuacionesIdentificacion_Service ss =
        new WsSIAConsultarActuacionesIdentificacion_Service(wsdlURL, SERVICE_NAME);
    WsSIAConsultarActuacionesIdentificacion port =
        ss.getWsSIAConsultarActuacionesIdentificacionSOAP();

    {
      System.out.println("Invoking consultarSIAV24...");
      es.mpt.dsic.eeutil.service.sia.model.ParamSIA2 _consultarSIAV24_parameters = null;
      es.mpt.dsic.eeutil.service.sia.model.EnviaSIA _consultarSIAV24__return =
          port.consultarSIAV24(_consultarSIAV24_parameters);
      System.out.println("consultarSIAV24.result=" + _consultarSIAV24__return);


    }
    {
      System.out.println("Invoking consultarSIA...");
      es.mpt.dsic.eeutil.service.sia.model.ParamSIA _consultarSIA_parameters = null;
      es.mpt.dsic.eeutil.service.sia.model.EnviaSIA3 _consultarSIA__return =
          port.consultarSIA(_consultarSIA_parameters);
      System.out.println("consultarSIA.result=" + _consultarSIA__return);


    }
    {
      System.out.println("Invoking consultarSIAV30...");
      es.mpt.dsic.eeutil.service.sia.model.ParamSIA3 _consultarSIAV30_parameters = null;
      es.mpt.dsic.eeutil.service.sia.model.EnviaSIA2 _consultarSIAV30__return =
          port.consultarSIAV30(_consultarSIAV30_parameters);
      System.out.println("consultarSIAV30.result=" + _consultarSIAV30__return);


    }

    System.exit(0);
  }

}
