package es.mpt.dsic.eeutil.operFirma.consumer.model;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.0.3 2016-01-28T11:15:49.416+01:00 Generated source
 * version: 3.0.3
 * 
 */
@WebServiceClient(name = "EeUtilServiceImplService",
    wsdlLocation = "http://127.0.0.1:8090/eeutil-oper-firma/ws/EeUtilService?wsdl",
    targetNamespace = "http://impl.service.ws.inside.dsic.mpt.es/")
public class EeUtilServiceImplService extends Service {

  public static final QName SERVICE =
      new QName("http://impl.service.ws.inside.dsic.mpt.es/", "EeUtilServiceImplService");
  public static final QName EeUtilServiceImplPort =
      new QName("http://impl.service.ws.inside.dsic.mpt.es/", "EeUtilServiceImplPort");

  public EeUtilServiceImplService(URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  public EeUtilServiceImplService(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public EeUtilServiceImplService() {
    super(null, SERVICE);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public EeUtilServiceImplService(WebServiceFeature... features) {
    super(null, SERVICE, features);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public EeUtilServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
    super(wsdlLocation, SERVICE, features);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public EeUtilServiceImplService(URL wsdlLocation, QName serviceName,
      WebServiceFeature... features) {
    super(wsdlLocation, serviceName, features);
  }

  /**
   *
   * @return returns EeUtilService
   */
  @WebEndpoint(name = "EeUtilServiceImplPort")
  public EeUtilService getEeUtilServiceImplPort() {
    return super.getPort(EeUtilServiceImplPort, EeUtilService.class);
  }

  /**
   * 
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *        Supported features not in the <code>features</code> parameter will have their default
   *        values.
   * @return returns EeUtilService
   */
  @WebEndpoint(name = "EeUtilServiceImplPort")
  public EeUtilService getEeUtilServiceImplPort(WebServiceFeature... features) {
    return super.getPort(EeUtilServiceImplPort, EeUtilService.class, features);
  }

}
