
package es.mpt.dsic.eeutil.operFirma.consumer.model;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.3 2016-01-28T11:15:49.372+01:00 Generated source
 * version: 3.0.3
 */

@WebFault(name = "ErrorTest", targetNamespace = "http://service.ws.inside.dsic.mpt.es/")
public class InSideException extends Exception {

  /**
   * 
   */
  private static final long serialVersionUID = 1L;

  private es.mpt.dsic.eeutil.operFirma.consumer.model.EstadoInfo errorTest;

  public InSideException() {
    super();
  }

  public InSideException(String message) {
    super(message);
  }

  public InSideException(String message, Throwable cause) {
    super(message, cause);
  }

  public InSideException(String message,
      es.mpt.dsic.eeutil.operFirma.consumer.model.EstadoInfo errorTest) {
    super(message);
    this.errorTest = errorTest;
  }

  public InSideException(String message,
      es.mpt.dsic.eeutil.operFirma.consumer.model.EstadoInfo errorTest, Throwable cause) {
    super(message, cause);
    this.errorTest = errorTest;
  }

  public es.mpt.dsic.eeutil.operFirma.consumer.model.EstadoInfo getFaultInfo() {
    return this.errorTest;
  }
}
